;;; company-stan-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from company-stan.el

(autoload 'company-stan-setup "company-stan" "\
Set up `company-stan-backend'.

Add `company-stan-backend' to `company-backends' buffer locally.

It is grouped with `company-dabbrev-code' because `company-stan-backend'
only performs completion based on predefined keywords in
`company-stan-keyword-list'.  See the help for `company-backends' for
details regarding grouped backends.

Add this function to the `stan-mode-hook'.")
(register-definition-prefixes "company-stan" '("company-stan-"))

;;; End of scraped data

(provide 'company-stan-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; company-stan-autoloads.el ends here
