;;; flycheck-stan-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from flycheck-stan.el

(autoload 'flycheck-stan-stanc2-setup "flycheck-stan" "\
Set up `flycheck' with `stanc' checker.")
(autoload 'flycheck-stan-stanc3-setup "flycheck-stan" "\
Set up `flycheck' with `stan3' checker.")
(register-definition-prefixes "flycheck-stan" '("flycheck-stan-"))

;;; End of scraped data

(provide 'flycheck-stan-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; flycheck-stan-autoloads.el ends here
