;;; stan-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from stan-keywords.el

(register-definition-prefixes "stan-keywords" '("stan-keywords--"))


;;; Generated autoloads from stan-mode.el

(autoload 'stan-mode "stan-mode" "\
A major mode for editing Stan files.

The hook `c-mode-common-hook' is run with no args at mode
initialization, then `stan-mode-hook'.

Key bindings:
\\{stan-mode-map}

(fn)" t)
(add-to-list 'auto-mode-alist `(,(rx (seq ".stan" eos)) . stan-mode))
(autoload 'stan-mode-setup "stan-mode" "\
Set up comment and indent style for `stan-mode'.")
(register-definition-prefixes "stan-mode" '("stan-"))

;;; End of scraped data

(provide 'stan-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; stan-mode-autoloads.el ends here
