;;; eldoc-stan-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from eldoc-stan.el

(autoload 'eldoc-stan-setup "eldoc-stan" "\
Set up `eldoc-stan-eldoc-documentation-function'.

Specify `eldoc-stan-eldoc-documentation-function' as
`eldoc-documentation-function'.
Add this function to the `stan-mode-hook'.")
(register-definition-prefixes "eldoc-stan" '("eldoc-stan-"))

;;; End of scraped data

(provide 'eldoc-stan-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; eldoc-stan-autoloads.el ends here
