;;; elysium-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from elysium.el

(autoload 'elysium-query "elysium" "\
Send USER-QUERY to elysium from the current buffer or chat buffer.

(fn USER-QUERY)" t)
(register-definition-prefixes "elysium" '("elysium-"))

;;; End of scraped data

(provide 'elysium-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; elysium-autoloads.el ends here
